# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ScoutAsia Engineering Dev-APJ (sae-mlp-sea-rg)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob download -c models -f model_deployment.zip -n model_deployment.zip --account-key $AZURE_STORAGE_KEY --account-name $AZURE_STORAGE_ACCOUNT
    failOnStandardError: true
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
